<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLctOlxa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLctOlxa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLctOlxa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLctOlxa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLctOlxa\App_KernelDevDebugContainer([
    'container.build_hash' => 'LctOlxa',
    'container.build_id' => 'e201a637',
    'container.build_time' => 1760687261,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLctOlxa');
