controllers:
    resource: ../src/Controller/
    type: attribute

homepage:
    path: /
    controller: App\Controller\HomeController::index

user_create:
    path: /user/create
    controller: App\Controller\HomeController::createUser
    methods: [POST]

team_create:
    path: /teams
    controller: App\Controller\TeamsController::createTeam
    methods: [POST]

team_list:
    path: /teams
    controller: App\Controller\TeamsController::listTeams
    methods: [GET]

team_update:
    path: /teams/{id}
    controller: App\Controller\TeamsController::updateTeam
    methods: [PUT]

team_delete:
    path: /teams/{id}
    controller: App\Controller\TeamsController::deleteTeam
    methods: [DELETE]