version: '3.8'

services:
  php:
    build: .
    container_name: symfony_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8000"
    command: php -S 0.0.0.0:8000 -t public
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgresql://symfony:symfony@database:5432/database?serverVersion=15&charset=utf8"
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-database}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-symfony}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-database}", "-U", "${POSTGRES_USER:-symfony}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###