<?php

namespace ContainerLctOlxa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QtBP2kNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QtBP2kN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QtBP2kN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ClockController::createClock' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ClockController::createClock()', 'getClockControllercreateClockService', true],
            'App\\Controller\\ClockController::getUserTeamClocks' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ClockController::getUserTeamClocks()', 'getClockControllergetUserTeamClocksService', true],
            'App\\Controller\\ClockController::deleteClock' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ClockController::deleteClock()', 'getClockControllerdeleteClockService', true],
            'App\\Controller\\ClockController::updateClock' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ClockController::updateClock()', 'getClockControllerupdateClockService', true],
            'App\\Controller\\TeamReportController::getTeamsAverageWorkTime' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\TeamReportController::getTeamsAverageWorkTime()', 'getTeamReportControllergetTeamsAverageWorkTimeService', true],
            'App\\Controller\\TeamsManagementController::createTeam' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\TeamsManagementController::createTeam()', 'getTeamsManagementControllercreateTeamService', true],
            'App\\Controller\\TeamsManagementController::listTeams' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\TeamsManagementController::listTeams()', 'getTeamsManagementControllerlistTeamsService', true],
            'App\\Controller\\TeamsManagementController::getTeam' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\TeamsManagementController::getTeam()', 'getTeamsManagementControllergetTeamService', true],
            'App\\Controller\\TeamsManagementController::updateTeam' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\TeamsManagementController::updateTeam()', 'getTeamsManagementControllerupdateTeamService', true],
            'App\\Controller\\TeamsManagementController::deleteTeam' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\TeamsManagementController::deleteTeam()', 'getTeamsManagementControllerdeleteTeamService', true],
            'App\\Controller\\KpiReportController::getEmployeeDailyWorkTime' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\KpiReportController::getEmployeeDailyWorkTime()', 'getUserReportControllergetEmployeeDailyWorkTimeService', true],
            'App\\Controller\\KpiReportController::getEmployeeAverageWorkTime' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\KpiReportController::getEmployeeAverageWorkTime()', 'getUserReportControllergetEmployeeAverageWorkTimeService', true],
            'App\\Controller\\KpiReportController::getGlobalReport' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\KpiReportController::getGlobalReport()', 'getUserReportControllergetGlobalReportService', true],
            'App\\Controller\\KpiReportController::getGlobalReportFiltered' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\KpiReportController::getGlobalReportFiltered()', 'getUserReportControllergetGlobalReportFilteredService', true],
            'App\\Controller\\UsersManagementController::createUser' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\UsersManagementController::createUser()', 'getUsersManagementControllercreateUserService', true],
            'App\\Controller\\UsersManagementController::deleteUser' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\UsersManagementController::deleteUser()', 'getUsersManagementControllerdeleteUserService', true],
            'App\\Controller\\UsersManagementController::displayUser' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\UsersManagementController::displayUser()', 'getUsersManagementControllerdisplayUserService', true],
            'App\\Controller\\UsersManagementController::showUser' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\UsersManagementController::showUser()', 'getUsersManagementControllershowUserService', true],
            'App\\Controller\\UsersManagementController::updateUser' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\UsersManagementController::updateUser()', 'getUsersManagementControllerupdateUserService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ClockController:createClock' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ClockController::createClock()', 'getClockControllercreateClockService', true],
            'App\\Controller\\ClockController:getUserTeamClocks' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ClockController::getUserTeamClocks()', 'getClockControllergetUserTeamClocksService', true],
            'App\\Controller\\ClockController:deleteClock' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ClockController::deleteClock()', 'getClockControllerdeleteClockService', true],
            'App\\Controller\\ClockController:updateClock' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ClockController::updateClock()', 'getClockControllerupdateClockService', true],
            'App\\Controller\\TeamReportController:getTeamsAverageWorkTime' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\TeamReportController::getTeamsAverageWorkTime()', 'getTeamReportControllergetTeamsAverageWorkTimeService', true],
            'App\\Controller\\TeamsManagementController:createTeam' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\TeamsManagementController::createTeam()', 'getTeamsManagementControllercreateTeamService', true],
            'App\\Controller\\TeamsManagementController:listTeams' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\TeamsManagementController::listTeams()', 'getTeamsManagementControllerlistTeamsService', true],
            'App\\Controller\\TeamsManagementController:getTeam' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\TeamsManagementController::getTeam()', 'getTeamsManagementControllergetTeamService', true],
            'App\\Controller\\TeamsManagementController:updateTeam' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\TeamsManagementController::updateTeam()', 'getTeamsManagementControllerupdateTeamService', true],
            'App\\Controller\\TeamsManagementController:deleteTeam' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\TeamsManagementController::deleteTeam()', 'getTeamsManagementControllerdeleteTeamService', true],
            'App\\Controller\\KpiReportController:getEmployeeDailyWorkTime' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\KpiReportController::getEmployeeDailyWorkTime()', 'getUserReportControllergetEmployeeDailyWorkTimeService', true],
            'App\\Controller\\KpiReportController:getEmployeeAverageWorkTime' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\KpiReportController::getEmployeeAverageWorkTime()', 'getUserReportControllergetEmployeeAverageWorkTimeService', true],
            'App\\Controller\\KpiReportController:getGlobalReport' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\KpiReportController::getGlobalReport()', 'getUserReportControllergetGlobalReportService', true],
            'App\\Controller\\KpiReportController:getGlobalReportFiltered' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\KpiReportController::getGlobalReportFiltered()', 'getUserReportControllergetGlobalReportFilteredService', true],
            'App\\Controller\\UsersManagementController:createUser' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\UsersManagementController::createUser()', 'getUsersManagementControllercreateUserService', true],
            'App\\Controller\\UsersManagementController:deleteUser' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\UsersManagementController::deleteUser()', 'getUsersManagementControllerdeleteUserService', true],
            'App\\Controller\\UsersManagementController:displayUser' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\UsersManagementController::displayUser()', 'getUsersManagementControllerdisplayUserService', true],
            'App\\Controller\\UsersManagementController:showUser' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\UsersManagementController::showUser()', 'getUsersManagementControllershowUserService', true],
            'App\\Controller\\UsersManagementController:updateUser' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\UsersManagementController::updateUser()', 'getUsersManagementControllerupdateUserService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ClockController::createClock' => '?',
            'App\\Controller\\ClockController::getUserTeamClocks' => '?',
            'App\\Controller\\ClockController::deleteClock' => '?',
            'App\\Controller\\ClockController::updateClock' => '?',
            'App\\Controller\\TeamReportController::getTeamsAverageWorkTime' => '?',
            'App\\Controller\\TeamsManagementController::createTeam' => '?',
            'App\\Controller\\TeamsManagementController::listTeams' => '?',
            'App\\Controller\\TeamsManagementController::getTeam' => '?',
            'App\\Controller\\TeamsManagementController::updateTeam' => '?',
            'App\\Controller\\TeamsManagementController::deleteTeam' => '?',
            'App\\Controller\\KpiReportController::getEmployeeDailyWorkTime' => '?',
            'App\\Controller\\KpiReportController::getEmployeeAverageWorkTime' => '?',
            'App\\Controller\\KpiReportController::getGlobalReport' => '?',
            'App\\Controller\\KpiReportController::getGlobalReportFiltered' => '?',
            'App\\Controller\\UsersManagementController::createUser' => '?',
            'App\\Controller\\UsersManagementController::deleteUser' => '?',
            'App\\Controller\\UsersManagementController::displayUser' => '?',
            'App\\Controller\\UsersManagementController::showUser' => '?',
            'App\\Controller\\UsersManagementController::updateUser' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ClockController:createClock' => '?',
            'App\\Controller\\ClockController:getUserTeamClocks' => '?',
            'App\\Controller\\ClockController:deleteClock' => '?',
            'App\\Controller\\ClockController:updateClock' => '?',
            'App\\Controller\\TeamReportController:getTeamsAverageWorkTime' => '?',
            'App\\Controller\\TeamsManagementController:createTeam' => '?',
            'App\\Controller\\TeamsManagementController:listTeams' => '?',
            'App\\Controller\\TeamsManagementController:getTeam' => '?',
            'App\\Controller\\TeamsManagementController:updateTeam' => '?',
            'App\\Controller\\TeamsManagementController:deleteTeam' => '?',
            'App\\Controller\\KpiReportController:getEmployeeDailyWorkTime' => '?',
            'App\\Controller\\KpiReportController:getEmployeeAverageWorkTime' => '?',
            'App\\Controller\\KpiReportController:getGlobalReport' => '?',
            'App\\Controller\\KpiReportController:getGlobalReportFiltered' => '?',
            'App\\Controller\\UsersManagementController:createUser' => '?',
            'App\\Controller\\UsersManagementController:deleteUser' => '?',
            'App\\Controller\\UsersManagementController:displayUser' => '?',
            'App\\Controller\\UsersManagementController:showUser' => '?',
            'App\\Controller\\UsersManagementController:updateUser' => '?',
        ]);
    }
}
