<?php

namespace ContainerLctOlxa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeamReportControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\TeamReportController' shared autowired service.
     *
     * @return \App\Controller\TeamReportController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/TeamReportController.php';

        return $container->services['App\\Controller\\TeamReportController'] = new \App\Controller\TeamReportController();
    }
}
