<?php

namespace ContainerLctOlxa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsersManagementControllerdeleteUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Kq27LHM.App\Controller\UsersManagementController::deleteUser()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Kq27LHM.App\\Controller\\UsersManagementController::deleteUser()'] = ($container->privates['.service_locator.Kq27LHM'] ?? $container->load('get_ServiceLocator_Kq27LHMService'))->withContext('App\\Controller\\UsersManagementController::deleteUser()', $container);
    }
}
